import React from "react";
import { Audio, Sequence, staticFile } from "remotion";
import { scenes } from "./theme";

// Flip to true once public/narration/*.mp3 and public/music.mp3 exist.
// The render script sets this via an env check on the public folder.
export const HAS_NARRATION = true;
export const HAS_MUSIC = true;

// Narration file per scene start frame. Each nX.mp3 is generated by
// scripts/narrate.mjs (Eleven Labs) from SCRIPT.md blocks.
const narration: { file: string; from: number }[] = [
  { file: "narration/n1.mp3", from: scenes.hook.from + 6 },
  { file: "narration/n2.mp3", from: scenes.problem.from + 6 },
  { file: "narration/n3.mp3", from: scenes.demoPass.from + 10 },
  { file: "narration/n4.mp3", from: scenes.demoFail.from + 6 },
  { file: "narration/n5.mp3", from: scenes.rules.from + 6 },
  { file: "narration/n6.mp3", from: scenes.specFirst.from + 6 },
  { file: "narration/n7.mp3", from: scenes.loops.from + 6 },
  { file: "narration/n8.mp3", from: scenes.makerChecker.from + 6 },
  { file: "narration/n9.mp3", from: scenes.outro.from + 6 },
];

export const Soundtrack: React.FC = () => {
  return (
    <>
      {HAS_MUSIC && (
        <Audio src={staticFile("music.mp3")} volume={0.16} loop />
      )}
      {HAS_NARRATION &&
        narration.map((n) => (
          <Sequence key={n.file} from={n.from}>
            <Audio src={staticFile(n.file)} volume={1} />
          </Sequence>
        ))}
    </>
  );
};
