// Package skeleton provides the static AGENTS.md skeleton generated by
// `agents-lint init` (FR-CLI-03). It is kept independent of cmd/ so its
// content can be validated against the real schema rules in a unit test
// without going through file I/O or Cobra.
package skeleton

// content is the AGENTS.md skeleton written by `agents-lint init`. It is
// intentionally minimal: valid YAML frontmatter, a top-level `## Agents`
// section, and a single agent block with a name, a role, and instructions —
// enough to satisfy rules S001-S005 with zero findings.
const content = `---
name: example-project
---

# AGENTS.md

## Agents

### Example Agent

Describe what this agent does and when it should be used.

**Role:** Describe what this agent is responsible for.

**Instructions:** Describe how this agent should behave.
`

// Content returns the static AGENTS.md skeleton written by `agents-lint
// init`.
func Content() []byte {
	return []byte(content)
}
